Add workaround for retry

diff --git a/.github/workflows/push.yml b/.github/workflows/push.yml
--- a/.github/workflows/push.yml
+++ b/.github/workflows/push.yml
@@ -159,8 +159,12 @@ jobs:
 
     # Generates an execution plan for Terraform
     - name: Terraform Plan
-      run: terraform plan -input=false
-      max_attempts: 3
+      run: |
+        # Retry 3 times before the steps actually fails
+        (echo "===== Terraform Plan Attempt: 1 ====" && terraform plan -input=false) || \
+        (echo "===== Terraform Plan Attempt: 2 ====" && terraform plan -input=false) || \
+        (echo "===== Terraform Plan Attempt: 3 ====" && terraform plan -input=false) || \
+        (echo "==== Terraform Plan Step Failed ====" && exit 1)
 
   security-scanning:
     name: 'security-scanning'
